const PRODUCT_CONFIG = {
  id: "mochila-antirrobo",
  origin: "landing_mochila_antirrobo",
  category: "Mochilas",
  name: "Mochila Antirrobo con Puerto USB",
  shortName: "Mochila Antirrobo",
  price: 189000,
  oldPrice: 269000,
  combo2: 339000,
  combo3: 459000,
  currency: "PYG",
  benefit: "Evitá robos y llevá tus cosas protegidas",
  buttonText: "Reservar con pago al recibir",
  checkoutTitle: "Reservá en menos de 1 minuto",
  metaTitle: "Mochila Antirrobo con Puerto USB | VG Shop Py",
  metaDescription: "Mochila antirrobo premium con puerto USB compatible con teléfonos Android y iPhone usando tu propio cable, material impermeable, compartimento para notebook y diseño ergonómico. Envíos a todo Paraguay y pago contra entrega en Asunción y Central.",
  heroTitle: "Mochila Antirrobo con Puerto USB",
  heroSubtitle: "Llevá tu notebook, documentos y celular más seguros en la calle, colectivo, moto, facultad u oficina. Diseño antirrobo, cierres protegidos, material impermeable y puerto USB para cargar usando tu power bank.",
  images:{
    hero:"IMG/Principal1.jpg",
    banner:"IMG/Principal2.jpg",
    img1:"IMG/Principal1.jpg",
    img2:"IMG/Principal2.jpg",
    img3:"39.jpg",
    img4:"40.jpg"
  },
  metaPixelId: '2412226475899711',
  supabaseUrl: 'https://roruinqorwgolcrhhmpm.supabase.co',
  supabaseAnonKey: 'sb_publishable_aRPb1yNunMEheat00BxwtQ_Uft732KJ',
  supabaseTable: 'pedidos_web',
};
