const PRODUCT_CONFIG = {
  id: "mochila-antirrobo",
  origin: "landing_mochila_antirrobo",
  category: "Mochilas",
  name: "Mochila Antirrobo con Puerto USB",
  shortName: "Mochila Antirrobo",
  price: 189000,
  oldPrice: 269000,
  combo2: 339000,
  combo3: 459000,
  currency: "PYG",
  benefit: "Protegé tus pertenencias todos los días",
  buttonText: "Comprar Ahora",
  checkoutTitle: "Completa tus datos",
  metaTitle: "Mochila Antirrobo con Puerto USB | VG Shop Py",
  metaDescription: "Mochila antirrobo premium con puerto USB compatible con teléfonos Android y iPhone usando tu propio cable, material impermeable, compartimento para notebook y diseño ergonómico. Envíos a todo Paraguay y pago contra entrega en Asunción y Central.",
  heroTitle: "Mochila Antirrobo con Puerto USB",
  heroSubtitle: "Protegé tu notebook, documentos y celular con una mochila moderna, impermeable y organizada. El puerto USB funciona con cualquier teléfono usando tu cable de carga y un power bank interno.",
  images:{
    hero:"IMG/Principal1.jpg",
    banner:"IMG/Principal2.jpg",
    img1:"IMG/Principal1.jpg",
    img2:"IMG/Principal2.jpg",
    img3:"39.jpg",
    img4:"40.jpg"
  },
  metaPixelId: '2412226475899711',
  supabaseUrl: 'https://roruinqorwgolcrhhmpm.supabase.co',
  supabaseAnonKey: 'sb_publishable_aRPb1yNunMEheat00BxwtQ_Uft732KJ',
  supabaseTable: 'pedidos_web',
};
